Martin's patch

diff --git a/debian/local/Xsession.d/20x11-common_process-args b/debian/local/Xsession.d/20x11-common_process-args
--- a/debian/local/Xsession.d/20x11-common_process-args
+++ b/debian/local/Xsession.d/20x11-common_process-args
@@ -2,6 +2,10 @@
 
 # This file is sourced by Xsession(5), not executed.
 
+# read OPTIONFILE
+OPTIONS=$(cat "$OPTIONFILE") || true
+
+
 # Determine how many arguments were provided.
 case $# in
   0)
@@ -12,7 +16,7 @@ case $# in
     case "$1" in
       failsafe)
         # Failsafe session was requested.
-        if grep -qs ^allow-failsafe "$OPTIONFILE"; then
+        if [ "${OPTIONS#*allow-failsafe}" != "$OPTIONS" ]; then
           if [ -e /usr/bin/x-terminal-emulator ]; then
             if [ -x /usr/bin/x-terminal-emulator ]; then
               exec x-terminal-emulator -geometry +1+1
