the xserver-xorg preinst. Properly handle the migration itself as well by   using better variables in the mv command. Thanks Justin Pryzby.   (closes: #331690) * Similarly separate the md5sum for the server symlink from the roster. Also   handle the case where the server symlink md5sum is removed but the symlink   itself is in place. Here we just remake the md5sum using that symlink   silently.

diff --git a/debian/xserver-xorg.preinst.in b/debian/xserver-xorg.preinst.in
--- a/debian/xserver-xorg.preinst.in
+++ b/debian/xserver-xorg.preinst.in
@@ -41,13 +41,21 @@ if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
     fi
   done
 
+  # If this checksum got removed on upgrade for some reason, re-add it
+  if ! [ -e "$SERVER_SYMLINK_CHECKSUM" ]; then
+    message "Server symlink checksum doesn't exist. We need to make it"
+    if [ -L "$SERVER_SYMLINK" ] ; then
+      message "Re-adding lost server symlink checksum"
+      readlink "$SERVER_SYMLINK" | md5sum > "$SERVER_SYMLINK_CHECKSUM"
+    fi
+  fi
+
   # the transition from /var/lib/xfree86 to /var/lib/x11 occurred in
-  # 7.0.0-0ubuntu1
+  # 7.0.0-0ubuntu1 and 1:7.0.0
   if [ -n "$UPGRADE" ] && \
-     dpkg --compare-versions "$2" lt "1:7.0.11"; then
+     dpkg --compare-versions "$2" lt "1:7.0.12"; then
     if [ -e "/var/lib/xfree86" ]; then
-      if [ -e "/var/lib/xfree86/$SERVER_SYMLINK_ROSTER_BASE" ] && \
-         [ -e "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE" ]; then
+      if [ -e "/var/lib/xfree86/$SERVER_SYMLINK_ROSTER_BASE" ]; then
         if fgrep -qx "$THIS_PACKAGE" \
            "/var/lib/xfree86/$SERVER_SYMLINK_ROSTER_BASE"; then
           # construct temporary roster file with our package name removed, ignoring
@@ -66,17 +74,22 @@ if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
             # no; remove both the original and our temporary copy
             rm -f "/var/lib/xfree86/$SERVER_SYMLINK_ROSTER_BASE" \
                   "/var/lib/xfree86/$SERVER_SYMLINK_ROSTER_BASE.dpkg-tmp"
-
-            # migrate the checksum if it doesn't exist
-            if [ -e "$SERVER_SYMLINK_CHECKSUM" ]; then
-              rm "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE"
-            else
-              mv "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE" \
-                 "$SERVER_SYMLINK_CHECKSUM"
-            fi
           fi
         fi
       fi
+
+      if [ -e "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE" ]; then
+        # migrate the checksum if it doesn't exist
+        if [ -e "$SERVER_SYMLINK_CHECKSUM" ]; then
+          message "Removing obsolete server symlink in /var/lib/xfree86"
+          rm "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE"
+        else
+          message "Migrating server symlink"
+          mv "/var/lib/xfree86/$SERVER_SYMLINK_CHECKSUM_BASE" \
+             "$CONFIG_AUX_DIR"
+        fi
+      fi
+
 
       if [ -e "/var/lib/xfree86/$XORGCONFIG_ROSTER_BASE" ]; then \
         if fgrep -qx "$THIS_PACKAGE" \
@@ -107,7 +120,8 @@ if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
           rm "/var/lib/xfree86/$XORGCONFIG_CHECKSUM_BASE"
         else
           mv "/var/lib/xfree86/$XORGCONFIG_CHECKSUM_BASE" \
-             "$XORGCONFIG_CHECKSUM"
+             "$CONFIG_AUX_DIR" || \
+                error "Could not move the xorg.conf.md5sum for some reason"
         fi
       fi
 
