* Only cleaning out old junk on upgrade and after version compare   This currently includes deregistering old debconf questions and removing   server symlink cruft. Closes: #451426, #451425, #451439

diff --git a/debian/xserver-xorg.postinst.in b/debian/xserver-xorg.postinst.in
--- a/debian/xserver-xorg.postinst.in
+++ b/debian/xserver-xorg.postinst.in
@@ -1748,18 +1748,20 @@ else
   debug_echo "not updating $XORGCONFIG; we're upgrading"
 fi
 
-# Clean up our old crap
-rm -f "$SERVER_SYMLINK_CHECKSUM" "$SERVER_SYMLINK_ROSTER"
-for QUESTION in "shared/default-x-server" "xserver-xorg/autodetect_mouse" \
-                "xserver-xorg/config/device/video_ram" \
-                "xserver-xorg/config/inputdevice/mouse/port" \
-                "xserver-xorg/config/inputdevice/mouse/protocol" \
-                "xserver-xorg/config/modules" \
-                "xserver-xorg/config/monitor/default-identifier" \
-                "xserver-xorg/config/monitor/identifier" \
-                "xserver-xorg/config/write_files_section"; do
-  db_unregister "$QUESTION" || true
-done
+if [ -n "$UPGRADE" ] && dpkg --compare-versions "$2" le "1:7.3+5"; then
+        # Clean up our old crap
+        rm -f "$SERVER_SYMLINK_CHECKSUM" "$SERVER_SYMLINK_ROSTER"
+        for QUESTION in "shared/default-x-server" "xserver-xorg/autodetect_mouse" \
+                        "xserver-xorg/config/device/video_ram" \
+                        "xserver-xorg/config/inputdevice/mouse/port" \
+                        "xserver-xorg/config/inputdevice/mouse/protocol" \
+                        "xserver-xorg/config/modules" \
+                        "xserver-xorg/config/monitor/default-identifier" \
+                        "xserver-xorg/config/monitor/identifier" \
+                        "xserver-xorg/config/write_files_section"; do
+          db_unregister "$QUESTION" || true
+        done
+fi
 
 exit 0
 
