* Don't bother at all with default-x-server question. Closes: #448863   + Remove it from the xserver-xorg postinst. Now instead of a complicated     md5sum, only create the symlink if nothing exists there.   + Make sure we delete the old md5sum and xserver roster files for this     stuff. We don't need it now.

diff --git a/debian/xserver-xorg.postinst.in b/debian/xserver-xorg.postinst.in
--- a/debian/xserver-xorg.postinst.in
+++ b/debian/xserver-xorg.postinst.in
@@ -666,38 +666,6 @@ fi
 
 debug_echo "Configuring $THIS_PACKAGE."
 
-# default X server
-
-# if the X server symlink file already exists and points to an executable X
-# server, it's not as important to ask questions related to it (these questions
-# "have a reasonable default")
-PRIORITY_CEILING=
-if [ -e "$SERVER_SYMLINK" ]; then
-  if [ -x "$(readlink "$SERVER_SYMLINK")" ]; then
-    debug_echo "X server symlink exists and points to executable X server;" \
-               "capping X server question priority at medium."
-    PRIORITY_CEILING=medium
-  fi
-fi
-
-# priority of shared/default-x-server
-PRIORITY=high
-
-db_metaget shared/default-x-server owners
-OWNERS="$RET"
-db_metaget shared/default-x-server choices
-CHOICES="$RET"
-
-if [ "$OWNERS" != "$CHOICES" ]; then
-  debug_echo "\$OWNERS does not equal \$CHOICES: \"$OWNERS\" != \"$CHOICES\""
-  db_subst shared/default-x-server choices $OWNERS
-  db_fset shared/default-x-server seen false
-fi
-
-if ! expr "$OWNERS" : ".*,.*" > /dev/null 2>&1; then
-  debug_echo "\$OWNERS has only one value; shared/default-x-server will not be asked"
-fi
-
 # collect information about installed video card(s), if possible
 case "$ARCH" in
   sparc)
@@ -1692,67 +1660,8 @@ done
 
 # only mess with the server symlink file if it is a symbolic link or does
 # not exist.  otherwise, assume that's the way the user wants it.
-if [ -L "$SERVER_SYMLINK" ] || ! [ -e "$SERVER_SYMLINK" ]; then
-  # migrate from old symlinks.
-  if [ "$(readlink /etc/X11/X)" = "/usr/X11R6/bin/Xorg" ] || \
-     [ "$(readlink /etc/X11/X)" = "/usr/bin/X11/Xorg" ] || \
-     [ "$(readlink /etc/X11/X)" = "/bin/true" ]; then
-    rm /etc/X11/X
-    ln -s $THIS_SERVER /etc/X11/X
-  fi
-
-  # apparently on some broken upgrades the SERVER_SYMLINK_CHECKSUM has been 
-  # lost. If it does not exists, make sure to recreate it.
-
-  if [ ! -e "$SERVER_SYMLINK_CHECKSUM" ] && [ -L "$SERVER_SYMLINK" ]; then
-    readlink "$SERVER_SYMLINK" | md5sum > "$SERVER_SYMLINK_CHECKSUM"
-  fi
-
-  # compare the current and stored checksums; if they do not match, assume
-  # that's the way the user wants it.
-  # why, why, why, why, why, why, why are we md5suming this? -daniels
-  if [ "$(readlink "$SERVER_SYMLINK" | md5sum)" = \
-       "$(cat "$SERVER_SYMLINK_CHECKSUM")" ] || \
-     [ "$(echo "/usr/X11R6/bin/Xorg" | md5sum)" = \
-       "$(cat "$SERVER_SYMLINK_CHECKSUM")" ] || \
-     [ "$(echo "/usr/bin/X11/Xorg" | md5sum)" = \
-       "$(cat "$SERVER_SYMLINK_CHECKSUM")" ] || \
-     [ "$(echo "/usr/bin/X11/XFree86" | md5sum)" = \
-       "$(cat "$SERVER_SYMLINK_CHECKSUM")" ] || \
-     [ "$(echo "/bin/true" | md5sum)" = \
-       "$(cat "$SERVER_SYMLINK_CHECKSUM")" ] || \
-     ! [ -e "$SERVER_SYMLINK" ]; then
-    # finally, only update the symlink if this package contains the
-    # selected default X server.
-    db_get shared/default-x-server
-    if [ -n "$RET" ]; then
-      SELECTED_PACKAGE="$RET"
-      if [ "$SELECTED_PACKAGE" = "$THIS_PACKAGE" ]; then
-        # prepare a new version of the config file; this is a symlink so we
-        # can't use the tempfile command for it (we'd have to subsequently
-        # use ln -sf, which is subject to race condition attacks)
-        NEW_SERVER_SYMLINK="$SERVER_SYMLINK.dpkg-new"
-        ln -sf "$THIS_SERVER" "$NEW_SERVER_SYMLINK"
-        if ! cmp -s "$SERVER_SYMLINK" "$NEW_SERVER_SYMLINK"; then
-          if [ "$(readlink "$SERVER_SYMLINK")" \
-               != "$(readlink "$NEW_SERVER_SYMLINK")" ]; then
-            mv "$NEW_SERVER_SYMLINK" "$SERVER_SYMLINK"
-            readlink "$SERVER_SYMLINK" | md5sum > \
-                     "$SERVER_SYMLINK_CHECKSUM"
-          fi
-        fi
-        rm -f "$NEW_SERVER_SYMLINK"
-      fi
-    else
-      warn "not updating $SERVER_SYMLINK; no default X server" \
-           "configured; run \"dpkg-reconfigure $THIS_PACKAGE\" to" \
-           "correct this"
-    fi
-  else
-    warn "not updating $SERVER_SYMLINK; file has been customized"
-  fi
-else
-  warn "not updating $SERVER_SYMLINK; file exists but is not a symlink"
+if ! [ -e "$SERVER_SYMLINK" ]; then
+  ln -s "$THIS_SERVER" "$SERVER_SYMLINK"
 fi
 
 # Don't touch the config on upgrades except to deal with known issues with old
@@ -1839,6 +1748,9 @@ if [ -z "$UPGRADE" ] || dpkg --compare-versions "$2" le "1:7.0.14"; then
 else
   debug_echo "not updating $XORGCONFIG; we're upgrading"
 fi
+
+# Clean up our old crap
+rm -f "$SERVER_SYMLINK_CHECKSUM" "$SERVER_SYMLINK_ROSTER"
 
 exit 0
 
